uses: actions/docker-build-push-gcr-update-gke-deployment-action@v1.4
with:
  service_account: ${{ secrests.GCLOUD_AUTH}} 
  zone: 'us-central1-c'
  project_id: 'clean-sylph-318816'
  registry: 'gcr.io'
  image_name: 'dev-fe'
  cluster: 'autopilot-cluster-1'
  namespace: 'default'
  deployment: 'front-end-dep'
  container: 'front-end'
