nname: ci

on:
  push:
    branches:
      - 'master'
 jobs:
  docker:
    runs-on: ubuntu-latest
  - uses: actions/checkout@v2
    name: Check out code
  - uses: mr-smithers-excellent/docker-build-push@v5
    name: Build & push Docker image
    with:
      image: repo/image
      tags: v1, latest
      registry: registry-url.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}




